const roles = {
  ADMIN: 'ADMIN',
  AGENTEVENTAS: 'AGENTEVENTAS',
  CLIENTECORPORATIVO: 'CLIENTECORPORATIVO',
  PROCESAMUESTRA: 'PROCESAMUESTRA',
  TOMAMUESTRA: 'TOMAMUESTRA',
  FACTURACION: 'FACTURACION',
  LABORATORIO: 'LABORATORIO',
  ORGANIZADOR: 'ORGANIZADOR',
  RECEPCION: 'RECEPCION',
};

export { roles };
